spring.application.name=api-java
server.port=${SERVER_PORT:8080}
server.shutdown=graceful
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
logging.structured.format.console=ecs
