{
 "title": "Application Health Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Go API Target Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(up{job=\"api-go\"})"
    }
   ]
  },
  {
   "title": "Java API Target Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "max(up{job=\"api-java\"})"
    }
   ]
  },
  {
   "title": "Go Process CPU Rate (sec/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"api-go\"}[5m]))",
     "legendFormat": "api-go"
    }
   ]
  },
  {
   "title": "Java Process CPU Rate (sec/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"api-java\"}[5m]))",
     "legendFormat": "api-java"
    }
   ]
  },
  {
   "title": "Go Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Java JVM Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{job=\"api-java\"})",
     "legendFormat": "threads_live"
    }
   ]
  }
 ]
}