replicaCount: 2

image:
  tag: staging

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4

resources:
  limits:
    cpu: 700m
    memory: 768Mi
  requests:
    cpu: 350m
    memory: 384Mi

networkPolicy:
  enabled: true
