replicaCount: 2

image:
  tag: staging

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4

resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 150m
    memory: 192Mi

networkPolicy:
  enabled: true
