global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api-go
    metrics_path: /metrics
    static_configs:
      - targets:
          - api-go:8080

  - job_name: api-java
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api-java:8080
